export default {
  name: "A",
  shape: [
    { x: 1.5, y: 1.5, z: 1.5, id: 0, keep: false },
    { x: 1.5, y: 1.5, z: -1.5, id: 3, keep: false },
    { x: 1.5, y: 0.5, z: 1.5, id: 4, keep: false },
    { x: 1.5, y: 0.5, z: -1.5, id: 7, keep: false },
    { x: 0.5, y: 1.5, z: 1.5, id: 16, keep: false },
    { x: 0.5, y: 1.5, z: 0.5, keep: true, id: 17 },
    { x: 0.5, y: 1.5, z: -0.5, keep: true, id: 18 },
    { x: 0.5, y: 1.5, z: -1.5, id: 19, keep: false },
    { x: 0.5, y: -0.5, z: 0.5, keep: true, id: 25 },
    { x: 0.5, y: -0.5, z: -0.5, keep: true, id: 26 },
    { x: 0.5, y: -1.5, z: 0.5, id: 29, keep: false },
    { x: 0.5, y: -1.5, z: -0.5, id: 30, keep: false },
    { x: -0.5, y: 1.5, z: 1.5, id: 32, keep: false },
    { x: -0.5, y: 1.5, z: 0.5, keep: true, id: 33 },
    { x: -0.5, y: 1.5, z: -0.5, keep: true, id: 34 },
    { x: -0.5, y: 1.5, z: -1.5, id: 35, keep: false },
    { x: -0.5, y: -0.5, z: 0.5, keep: true, id: 41 },
    { x: -0.5, y: -0.5, z: -0.5, keep: true, id: 42 },
    { x: -0.5, y: -1.5, z: 0.5, id: 45, keep: false },
    { x: -0.5, y: -1.5, z: -0.5, id: 46, keep: false },
    { x: -1.5, y: 1.5, z: 1.5, id: 48, keep: false },
    { x: -1.5, y: 1.5, z: -1.5, id: 51, keep: false },
    { x: -1.5, y: 0.5, z: 1.5, id: 52, keep: false },
    { x: -1.5, y: 0.5, z: -1.5, id: 55, keep: false },
    {
      x: -0.5,
      y: 0.5,
      z: 1.5,
      keep: true,
      id: 36,
      clues: [{ number: 2, face: { z: 1 } }],
    },
    {
      x: -0.5,
      y: 0.5,
      z: -1.5,
      keep: true,
      id: 39,
      clues: [{ number: 2, face: { z: 1 } }],
    },
    {
      x: -0.5,
      y: 0.5,
      z: 0.5,
      id: 37,
      keep: false,
      clues: [
        { number: 2, face: { z: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: -0.5,
      y: 0.5,
      z: -0.5,
      id: 38,
      keep: false,
      clues: [
        { number: 2, face: { z: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: 0.5,
      y: 0.5,
      z: 1.5,
      keep: true,
      id: 20,
      clues: [{ number: 2, face: { z: 1 } }],
    },
    {
      x: 0.5,
      y: 0.5,
      z: -1.5,
      keep: true,
      id: 23,
      clues: [{ number: 2, face: { z: 1 } }],
    },
    {
      x: 0.5,
      y: 0.5,
      z: 0.5,
      id: 21,
      keep: false,
      clues: [
        { number: 2, face: { z: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: 0.5,
      y: 0.5,
      z: -0.5,
      id: 22,
      keep: false,
      clues: [
        { number: 2, face: { z: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: 0.5,
      y: -0.5,
      z: -1.5,
      keep: true,
      id: 27,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: -0.5,
      y: -0.5,
      z: -1.5,
      keep: true,
      id: 43,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: 0.5,
      y: -1.5,
      z: -1.5,
      keep: true,
      id: 31,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: -0.5,
      y: -1.5,
      z: -1.5,
      keep: true,
      id: 47,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: 0.5,
      y: -0.5,
      z: 1.5,
      keep: true,
      id: 24,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: -0.5,
      y: -0.5,
      z: 1.5,
      keep: true,
      id: 40,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: 0.5,
      y: -1.5,
      z: 1.5,
      keep: true,
      id: 28,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: -0.5,
      y: -1.5,
      z: 1.5,
      keep: true,
      id: 44,
      clues: [{ number: 2, face: { x: -1 } }],
    },
    {
      x: -1.5,
      y: -0.5,
      z: -1.5,
      id: 59,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -0.5,
      z: 1.5,
      id: 56,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -1.5,
      z: -1.5,
      id: 63,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -1.5,
      z: 1.5,
      id: 60,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -0.5,
      z: -1.5,
      id: 11,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -0.5,
      z: 1.5,
      id: 8,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -1.5,
      z: -1.5,
      id: 15,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -1.5,
      z: 1.5,
      id: 12,
      keep: false,
      clues: [
        { number: 0, face: { z: -1 } },
        { number: 2, face: { x: -1 } },
      ],
    },
    {
      x: -1.5,
      y: 1.5,
      z: -0.5,
      id: 50,
      keep: false,
      clues: [{ number: 0, face: { y: 1 } }],
    },
    {
      x: -1.5,
      y: 0.5,
      z: -0.5,
      id: 54,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -0.5,
      z: -0.5,
      id: 58,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -1.5,
      z: -0.5,
      id: 62,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: -1.5,
      y: 1.5,
      z: 0.5,
      id: 49,
      keep: false,
      clues: [{ number: 0, face: { y: 1 } }],
    },
    {
      x: -1.5,
      y: 0.5,
      z: 0.5,
      id: 53,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -0.5,
      z: 0.5,
      id: 57,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: -1.5,
      y: -1.5,
      z: 0.5,
      id: 61,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: 1.5,
      y: 1.5,
      z: -0.5,
      id: 2,
      keep: false,
      clues: [{ number: 0, face: { y: 1 } }],
    },
    {
      x: 1.5,
      y: 0.5,
      z: -0.5,
      id: 6,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -0.5,
      z: -0.5,
      id: 10,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -1.5,
      z: -0.5,
      id: 14,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: 1.5,
      y: 1.5,
      z: 0.5,
      id: 1,
      keep: false,
      clues: [{ number: 0, face: { y: 1 } }],
    },
    {
      x: 1.5,
      y: 0.5,
      z: 0.5,
      id: 5,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { x: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -0.5,
      z: 0.5,
      id: 9,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
    {
      x: 1.5,
      y: -1.5,
      z: 0.5,
      id: 13,
      keep: false,
      clues: [
        { number: 0, face: { y: 1 } },
        { number: 0, face: { z: -1 } },
      ],
    },
  ],
};
